{
  "test_case": "div_posint_to_neginto.json",
  "description": "Execution Failed",
  "status": "FAIL",
  "error": "Expected 5, got 0.6666666666666666",
  "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\jkcho\\tossify-qa\\runner.py\", line 39, in run_test_case\n    result = test_func(**test_case[\"parameters\"])\n  File \"C:\\Users\\jkcho\\tossify-qa\\tests/functions.py\", line 23, in divide_test\n    assert abs(result - expected) < 1e-6, f\"Expected {expected}, got {result}\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAssertionError: Expected 5, got 0.6666666666666666\n",
  "log": "Dividing 2 / 3\nResult: 0.6666666666666666\n",
  "timestamp": "2025-04-07T17:09:57.884240",
  "duration": 0.004
}